# Advanced Metering Infrastructure (AMI) Integration
# Engineering Department Energy Trading System

ami:
  network_type: "engineering_private"
  validator: "engineering_department"
  communication: 
    protocol: "TLS_1_3_ENCRYPTED"
    network: "university_campus_network"
    isolation: "air_gapped"
  
  smart_meters:
    total_count: 15
    building: "Engineering Complex"
    meter_ids: ["ENG_001", "ENG_002", "ENG_003", "ENG_004", "ENG_005", "ENG_006", "ENG_007", "ENG_008", "ENG_009", "ENG_010", "ENG_011", "ENG_012", "ENG_013", "ENG_014", "ENG_015"]
    energy_sources: ["solar_panels_50kw", "grid_connection", "battery_storage_10kwh"]
        
  data_collection:
    interval: "15_minutes"
    encryption: "AES_256"
    backup_frequency: "hourly"
    retention_period: "7_years"
    
  oracle_integration:
    submission_frequency: "15_minutes"
    validation_node: "engineering"
    consensus_threshold: 1
    single_validator_mode: true
    
blockchain_integration:
  oracle_program: "OracleEngDeptAMI1234567890123456789"
  submission_account: "engineering_ami_oracle"
  validation_required: true
  rec_certificate_validation: true
  validator_authority: "engineering_department"
