[toolchain]

[features]
resolution = true
skip-lint = false

[programs.campus]
registry = "RegEngDeptEnergyP2P1234567890123456789"
energy_token = "EnergyTokenEngDept1234567890123456789" 
trading = "TradingEngDeptP2P1234567890123456789"
oracle = "OracleEngDeptAMI1234567890123456789"
governance = "GovernanceEngDeptPoA1234567890123456789"

[registry]
url = "http://engineering-validator.campus.local:8899"

[provider]
cluster = "http://engineering-validator.campus.local:8899"
wallet = "/opt/campus-blockchain/admin/engineering-admin-keypair.json"

[scripts]
deploy-production = "anchor deploy --program-name registry --program-name energy_token --program-name trading --program-name oracle --program-name governance"
verify-deployment = "anchor test --skip-deploy"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgrade_wait = 3000
