# Engineering Department Operations Configuration
# University P2P Energy Trading System
# Updated: September 12, 2025
# Platform: Solana/Anchor

[system]
platform = "solana"
network_type = "private"
deployment_date = "2025-09-12"
version = "1.0.0"

[validator]
department = "engineering"
authority_level = "FULL_AUTHORITY"
network_role = "sole_validator"
consensus_mechanism = "proof_of_stake"
rpc_endpoint = "http://localhost:8899"

[rec_validation]
enabled = true
certificate_authority = true  
single_signature_mode = true
engineering_authority = true
sustainability_coordination = true

[operations]
auto_market_clearing = true
meter_data_validation = true
emergency_pause_authority = true
audit_logging = true
system_administration = true

[network]
campus_only = true
external_connectivity = false
single_validator_consensus = true

[security]
key_management = "engineering_department"
access_control = "engineering_specific" 
encryption = "campus_standard"
backup_procedures = "engineering_managed"

[rec_policies]
# REC validation by Engineering Department
solar_rec_rate = 1.0  # 1 REC per kWh solar
grid_rec_rate = 0.0   # No RECs for grid electricity
battery_storage_eligible = true
engineering_oversight = true

[market_operations]
clearing_frequency = "hourly"
price_discovery = "automatic"
order_matching = "fifo"  # First In, First Out
settlement = "automatic"
escrow_management = true
platform_integration = "solana_anchor"

[programs]
# Solana Program IDs for Engineering Department
registry = "RegEngDeptEnergyP2P1234567890123456789"
energy_token = "EnergyTokenEngDept1234567890123456789"
trading = "TradingEngDeptP2P1234567890123456789"
oracle = "OracleEngDeptAMI1234567890123456789"
governance = "GovernanceEngDeptPoA1234567890123456789"

[monitoring]
enabled = true
metrics_collection = true
performance_tracking = true
alert_system = true
dashboard_url = "http://localhost:3000"
