version: '3.8'

# Development override - use with: docker compose -f docker-compose.yml -f docker-compose.dev.yml up
services:
  api-gateway-dev:
    build:
      dockerfile: docker/api-gateway/Dockerfile.dev
    environment:
      - RUST_LOG=debug,tower_http=debug,axum::rejection=trace
      - RUST_BACKTRACE=1
      - PORT=3000
    volumes:
      - ../../api-gateway:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
      # Exclude target from host mount to avoid conflicts
      - /app/target
    healthcheck:
      interval: 45s
      timeout: 15s
      retries: 3
      start_period: 30s
    stdin_open: true
    tty: true
