version: '3.8'

# Production override - use with: docker compose -f docker-compose.yml -f docker-compose.prod.yml up
services:
  api-gateway:
    build:
      dockerfile: docker/api-gateway/Dockerfile
    environment:
      - RUST_LOG=info,tower_http=info
      - PORT=3000
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
