name: Smart Contracts CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'contracts/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/contracts.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'contracts/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  check:
    name: Check Smart Contracts
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        components: rustfmt, clippy

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Cache cargo registry and target
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('contracts/**/*.rs') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-cargo-

    - name: Cache cargo-contract installation
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-contract
        key: ${{ runner.os }}-cargo-contract-4.1.1
        restore-keys: |
          ${{ runner.os }}-cargo-contract-

    - name: Install cargo-contract
      run: |
        if ! command -v cargo-contract &> /dev/null; then
          cargo install --force --locked cargo-contract --version 4.1.1
        else
          echo "cargo-contract already installed"
        fi

    - name: Check code formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo test --all-features --workspace

  build:
    name: Build Smart Contracts
    runs-on: ubuntu-latest
    needs: check
    
    strategy:
      matrix:
        contract: [registry, grid-token, trading, oracle-client]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3

    - name: Cache cargo registry and contract targets
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          contracts/${{ matrix.contract }}/target/
        key: ${{ runner.os }}-cargo-contract-${{ matrix.contract }}-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('contracts/${{ matrix.contract }}/**/*.rs') }}
        restore-keys: |
          ${{ runner.os }}-cargo-contract-${{ matrix.contract }}-${{ hashFiles('**/Cargo.lock') }}-
          ${{ runner.os }}-cargo-contract-${{ matrix.contract }}-
          ${{ runner.os }}-cargo-

    - name: Cache cargo-contract installation
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-contract
        key: ${{ runner.os }}-cargo-contract-4.1.1
        restore-keys: |
          ${{ runner.os }}-cargo-contract-

    - name: Install cargo-contract
      run: |
        if ! command -v cargo-contract &> /dev/null; then
          cargo install --force --locked cargo-contract --version 4.1.1
        else
          echo "cargo-contract already installed"
        fi

    - name: Build contract - ${{ matrix.contract }}
      run: |
        cd contracts/${{ matrix.contract }}
        cargo contract build --release --quiet

    - name: Upload contract artifacts
      uses: actions/upload-artifact@v4
      with:
        name: contract-${{ matrix.contract }}
        path: |
          contracts/${{ matrix.contract }}/target/ink/${{ matrix.contract }}/${{ matrix.contract }}.contract
          contracts/${{ matrix.contract }}/target/ink/${{ matrix.contract }}/metadata.json
        retention-days: 30

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: check
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Cache cargo registry and audit tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/bin/cargo-audit
          target/
        key: ${{ runner.os }}-cargo-audit-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-audit-
          ${{ runner.os }}-cargo-

    - name: Install cargo-audit
      run: |
        if ! command -v cargo-audit &> /dev/null; then
          cargo install --force cargo-audit
        else
          echo "cargo-audit already installed"
        fi

    - name: Run security audit
      run: cargo audit

  deploy-testnet:
    name: Deploy to Testnet
    runs-on: ubuntu-latest
    needs: [build, security-audit]
    if: github.ref == 'refs/heads/main'
    environment: testnet
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download contract artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./contract-artifacts
        pattern: contract-*
        merge-multiple: true

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Cache cargo-contract installation
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-contract
        key: ${{ runner.os }}-cargo-contract-4.1.1
        restore-keys: |
          ${{ runner.os }}-cargo-contract-

    - name: Install cargo-contract
      run: |
        if ! command -v cargo-contract &> /dev/null; then
          cargo install --force --locked cargo-contract --version 4.1.1
        else
          echo "cargo-contract already installed"
        fi

    - name: Setup deployment environment
      run: |
        echo "SUBSTRATE_URL=${{ secrets.TESTNET_SUBSTRATE_URL }}" >> $GITHUB_ENV
        echo "DEPLOYER_SEED=${{ secrets.TESTNET_DEPLOYER_SEED }}" >> $GITHUB_ENV

    - name: Deploy contracts to testnet
      run: |
        # This would contain the actual deployment script
        echo "Deploying to testnet..."
        echo "Substrate URL: $SUBSTRATE_URL"
        # Add actual deployment logic here
        
    - name: Create deployment summary
      run: |
        echo "## 🚀 Testnet Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Network**: Testnet" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Deployed At**: $(date -u)" >> $GITHUB_STEP_SUMMARY

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: p2p_energy_trading
          POSTGRES_USER: p2p_user
          POSTGRES_PASSWORD: p2p_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'docker/*/package-lock.json'

    - name: Install dependencies
      run: |
        cd docker/api-gateway && npm ci
        cd ../oracle-simulator && npm ci

    - name: Download contract artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./contract-artifacts
        pattern: contract-*
        merge-multiple: true

    - name: Run integration tests
      run: |
        echo "Running integration tests..."
        # Add actual integration test commands here
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results
        path: |
          test-results/
          logs/
        retention-days: 7
